<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Diskon</name>
   <tag></tag>
   <elementGuidId>e740488f-a48a-49ab-835c-c834f1d65f10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.gift</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>be702542-b77e-498f-8b73-9a9b2698f043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gift</value>
      <webElementGuid>324a62ed-d399-45ac-bfb4-de57bf54ccd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./static/media/gift.29054bf72acf5128feda.png</value>
      <webElementGuid>d4f93692-818d-43fb-9f4e-57121d29f6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>gift box</value>
      <webElementGuid>455113c6-5d19-439f-838e-fc2a887acdba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;pb-5&quot;]/div[@class=&quot;container section-5 text-center&quot;]/img[@class=&quot;gift&quot;]</value>
      <webElementGuid>7afbfe6d-878c-4edd-864c-0b5bf9e54a4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/img</value>
      <webElementGuid>d126f2db-93c7-4270-92d2-2ee295537968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='gift box']</value>
      <webElementGuid>1ec2adf4-4ecf-4130-a64d-4a5898f9eb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>4fe0140c-e80c-4db0-bfab-f684900a099b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './static/media/gift.29054bf72acf5128feda.png' and @alt = 'gift box']</value>
      <webElementGuid>ab32b128-08b4-43d4-bece-c182ad370d30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
