<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Bulan Ramadan Banyak Diskon</name>
   <tag></tag>
   <elementGuidId>0ac5dc78-0b11-43de-8766-4a9e9ebd7a1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#banner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='banner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>4250901e-9a59-4293-9c0c-a479e9b35521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h2-section-5 justify-content-start</value>
      <webElementGuid>4716f315-e7a4-4979-9131-641a7ed5a753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>banner</value>
      <webElementGuid>afbcb3ca-d1dc-4466-8277-60061238b38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bulan Ramadan Banyak Diskon!</value>
      <webElementGuid>1897a5c6-9424-43e1-917c-7e2129643ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;banner&quot;)</value>
      <webElementGuid>c44f2ff3-aeff-4f61-83b8-45dec980c27d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='banner']</value>
      <webElementGuid>ddd548ad-7830-483f-9f2b-06ec6bd12356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/h2</value>
      <webElementGuid>72b28d7e-7f60-4d92-873f-b5d4de632c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[2]/following::h2[1]</value>
      <webElementGuid>3c08c186-859d-4999-b617-87aabba9901f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[2]/following::h2[1]</value>
      <webElementGuid>77ba0ee1-d64a-4d8b-a6f6-a7226ca96161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diskon Hingga 60%'])[1]/preceding::h2[1]</value>
      <webElementGuid>dfa40071-f90c-498f-b54b-bda17b0d0ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telusuri Kategori'])[1]/preceding::h2[1]</value>
      <webElementGuid>9d3d150f-0f7d-4979-92d6-4505a5e1e0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bulan Ramadan Banyak Diskon!']/parent::*</value>
      <webElementGuid>5bbaf0a9-2432-4a54-a61c-ccd72c386294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>7d23ff44-c486-433a-866f-9d834d118cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'banner' and (text() = 'Bulan Ramadan Banyak Diskon!' or . = 'Bulan Ramadan Banyak Diskon!')]</value>
      <webElementGuid>d334c030-9b16-401f-94cf-d5ff6fc50872</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
